export const ADMIN_DEMO_SUBSCRIBERS = [
  {
    id: 'sub-001',
    account_number: 'AV-BTG-10234',
    first_name: 'Maria',
    last_name: 'Santos',
    mobile: '09171234567',
    email: 'maria.santos@gmail.com',
    province: 'Batangas',
    municipality: 'Lipa City',
    barangay: 'San Pedro',
    subscription_status: 'active',
    plan_name: 'Fiber 100 Mbps',
    monthly_fee: 1799,
    outstanding_balance: 1799,
    enrichment_pct: 37,
    points_balance: 230,
    referral_code: 'SANT-4821-BTG',
    app_last_login: '2025-07-09T08:00:00Z',
    hubspot_contact_id: 'hs-contact-001',
  },
  {
    id: 'sub-002',
    account_number: 'AV-BTG-10198',
    first_name: 'Jose',
    last_name: 'Reyes',
    mobile: '09289876543',
    email: 'jose.reyes@gmail.com',
    province: 'Batangas',
    municipality: 'Batangas City',
    barangay: 'Kumintang Ibaba',
    subscription_status: 'active',
    plan_name: 'Fiber 50 Mbps',
    monthly_fee: 1299,
    outstanding_balance: 0,
    enrichment_pct: 87,
    points_balance: 580,
    referral_code: 'REYE-3310-BTG',
    app_last_login: '2025-07-08T15:30:00Z',
    hubspot_contact_id: 'hs-contact-002',
  },
  {
    id: 'sub-003',
    account_number: 'AV-QUE-20045',
    first_name: 'Ana',
    last_name: 'Cruz',
    mobile: '09151112233',
    email: 'ana.cruz@yahoo.com',
    province: 'Quezon Province',
    municipality: 'Lucena City',
    barangay: 'Ibabang Dupay',
    subscription_status: 'suspended',
    plan_name: 'Fiber 100 Mbps',
    monthly_fee: 1799,
    outstanding_balance: 3598,
    enrichment_pct: 12,
    points_balance: 50,
    referral_code: 'CRUZ-7742-QUE',
    app_last_login: '2025-06-15T10:00:00Z',
    hubspot_contact_id: null,
  },
  {
    id: 'sub-004',
    account_number: 'AV-ZAM-30012',
    first_name: 'Roberto',
    last_name: 'Dela Torre',
    mobile: '09334445566',
    email: null,
    province: 'Zambales',
    municipality: 'Olongapo City',
    barangay: 'Barretto',
    subscription_status: 'active',
    plan_name: 'Fiber 200 Mbps',
    monthly_fee: 2499,
    outstanding_balance: 0,
    enrichment_pct: 62,
    points_balance: 310,
    referral_code: 'DELA-9901-ZAM',
    app_last_login: '2025-07-09T07:45:00Z',
    hubspot_contact_id: 'hs-contact-004',
  },
];

export const ADMIN_DEMO_TICKETS = [
  {
    id: 'tkt-001', ticket_number: 'AV-TKT-20250010',
    subscriber_name: 'Maria Santos', account_number: 'AV-BTG-10234',
    ticket_type: 'technical', category: 'Slow speed',
    subject: 'Internet is slower than usual during evenings',
    description: 'Connection consistently drops to 10-15 Mbps after 7pm. Normal speed is 100 Mbps. Issue started last week. Router shows green lights. Already tried restarting.',
    status: 'in_progress', priority: 'normal', assigned_agent: 'Jomar Santos',
    created_at: '2025-07-05T10:00:00Z', due_date: '2025-07-12T00:00:00Z',
    hubspot_ticket_id: 'hs-tkt-001',
  },
  {
    id: 'tkt-002', ticket_number: 'AV-TKT-20250009',
    subscriber_name: 'Ana Cruz', account_number: 'AV-QUE-20045',
    ticket_type: 'billing', category: 'Payment not reflected',
    subject: 'Paid last month but account still shows overdue',
    description: 'I paid PHP 1,799 via GCash on June 10. Transaction reference: GC20250610-XXXXX. The app still shows my account as overdue. Please check.',
    status: 'open', priority: 'high', assigned_agent: null,
    created_at: '2025-07-03T14:00:00Z', due_date: '2025-07-08T00:00:00Z',
    hubspot_ticket_id: null,
  },
  {
    id: 'tkt-003', ticket_number: 'AV-TKT-20250008',
    subscriber_name: 'Jose Reyes', account_number: 'AV-BTG-10198',
    ticket_type: 'technical', category: 'No internet',
    subject: 'Complete internet outage after storm',
    description: 'Total loss of internet connection since July 1 after the storm. Router is offline. Checked all cables - no visible damage. Neighbors in same area also affected.',
    status: 'resolved', priority: 'urgent', assigned_agent: 'Jomar Santos',
    created_at: '2025-07-01T09:00:00Z', due_date: '2025-07-03T00:00:00Z',
    hubspot_ticket_id: 'hs-tkt-003',
  },
  {
    id: 'tkt-004', ticket_number: 'AV-TKT-20250007',
    subscriber_name: 'Roberto Dela Torre', account_number: 'AV-ZAM-30012',
    ticket_type: 'technical', category: 'Wi-Fi issue',
    subject: 'Wi-Fi signal weak in certain rooms',
    description: 'Router is in living room but signal drops in the bedroom and garage. House is roughly 120sqm. Currently on Fiber 200.',
    status: 'open', priority: 'normal', assigned_agent: 'Ana Reyes',
    created_at: '2025-07-07T11:00:00Z', due_date: '2025-07-14T00:00:00Z',
    hubspot_ticket_id: null,
  },
  {
    id: 'tkt-005', ticket_number: 'AV-TKT-20250006',
    subscriber_name: 'Maria Santos', account_number: 'AV-BTG-10234',
    ticket_type: 'billing', category: 'Dispute',
    subject: 'Charged twice for June billing period',
    description: 'My statement shows two charges of PHP 1,799 for the same billing period (June 1-30). I only have one account.',
    status: 'open', priority: 'high', assigned_agent: null,
    created_at: '2025-07-08T09:30:00Z', due_date: '2025-07-10T00:00:00Z',
    hubspot_ticket_id: null,
  },
  {
    id: 'tkt-006', ticket_number: 'AV-TKT-20250005',
    subscriber_name: 'Jose Reyes', account_number: 'AV-BTG-10198',
    ticket_type: 'technical', category: 'Slow speed',
    subject: 'Upload speed significantly lower than plan',
    description: 'Download is fine at 48 Mbps but upload is only 3-5 Mbps. On Fiber 50 which should have symmetric speeds.',
    status: 'closed', priority: 'low', assigned_agent: 'Jomar Santos',
    created_at: '2025-06-25T10:00:00Z', due_date: '2025-07-02T00:00:00Z',
    hubspot_ticket_id: 'hs-tkt-006',
  },
];

export const ADMIN_DEMO_TICKET_COMMENTS: Record<string, { id: string; author: string; avatar: string; message: string; created_at: string; is_internal?: boolean }[]> = {
  'tkt-001': [
    { id: 'c1', author: 'Jomar Santos', avatar: 'JS', message: 'Investigating the issue. Preliminary check shows congestion in the Lipa City node during peak hours. Escalating to NOC team.', created_at: '2025-07-05T14:00:00Z' },
    { id: 'c2', author: 'Maria Santos', avatar: 'MS', message: 'Thank you for the update. Is there an estimated time for the fix?', created_at: '2025-07-06T08:30:00Z' },
    { id: 'c3', author: 'Jomar Santos', avatar: 'JS', message: 'NOC has identified the issue - a failing switch in the node. Replacement scheduled for July 10. We expect full speeds to be restored by then.', created_at: '2025-07-06T15:00:00Z', is_internal: false },
  ],
  'tkt-002': [
    { id: 'c4', author: 'System', avatar: 'SY', message: 'Ticket received. Assigned to billing team for review.', created_at: '2025-07-03T14:05:00Z' },
  ],
  'tkt-003': [
    { id: 'c5', author: 'Ana Reyes', avatar: 'AR', message: 'Field team dispatched to the Batangas area to assess storm damage to infrastructure.', created_at: '2025-07-01T11:00:00Z' },
    { id: 'c6', author: 'Ana Reyes', avatar: 'AR', message: 'Infrastructure repair completed. Service restored to affected subscribers.', created_at: '2025-07-02T16:30:00Z' },
    { id: 'c7', author: 'Jose Reyes', avatar: 'JR', message: 'Internet is back! Thank you for the quick response.', created_at: '2025-07-02T18:00:00Z' },
  ],
};

export const ADMIN_DEMO_HUBSPOT_LOGS = [
  { id: 'hs-1', entity_type: 'subscriber', entity_id: 'sub-001', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-09T08:00:00Z', error_message: null },
  { id: 'hs-2', entity_type: 'ticket', entity_id: 'tkt-001', hubspot_object_type: 'ticket', action: 'create', status: 'success', synced_at: '2025-07-05T10:01:00Z', error_message: null },
  { id: 'hs-3', entity_type: 'subscriber', entity_id: 'sub-003', hubspot_object_type: 'contact', action: 'create', status: 'failed', synced_at: null, error_message: 'Invalid phone format for HubSpot contact' },
  { id: 'hs-4', entity_type: 'ticket', entity_id: 'tkt-002', hubspot_object_type: 'ticket', action: 'create', status: 'pending', synced_at: null, error_message: null },
  { id: 'hs-5', entity_type: 'subscriber', entity_id: 'sub-004', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-09T07:46:00Z', error_message: null },
  { id: 'hs-6', entity_type: 'payment', entity_id: 'pay-002', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-08T12:00:00Z', error_message: null },
];

export const ADMIN_DEMO_PROMOS = [
  { id: 'promo-001', title: 'OFW Family Package', subtitle: 'Stay connected with family abroad', body: 'Upgrade to Fiber 200 and get 2 months free!', cta_text: 'Learn More', promo_type: 'discount', target_tags: ['ofw'], is_active: true, starts_at: '2025-07-01', ends_at: '2025-07-31', sort_order: 1 },
  { id: 'promo-002', title: 'Refer a Neighbor', subtitle: 'Earn PHP 200 bill credit', body: 'Every successful referral gives you PHP 200 off your next bill.', cta_text: 'Share My Code', promo_type: 'announcement', target_tags: [], is_active: true, starts_at: '2025-06-01', ends_at: null, sort_order: 2 },
  { id: 'promo-003', title: 'Free Installation Until July 31', subtitle: 'New subscribers only', body: 'New subscribers get free installation on all Fiber plans.', cta_text: 'Refer a Friend', promo_type: 'discount', target_tags: [], is_active: true, starts_at: '2025-07-01', ends_at: '2025-07-31', sort_order: 3 },
  { id: 'promo-004', title: 'Gaming Fiber 200 Bundle', subtitle: 'Low latency for serious gamers', body: 'Get Fiber 200 at Fiber 100 price for 3 months. Gamers only.', cta_text: 'Upgrade Now', promo_type: 'discount', target_tags: ['gaming'], is_active: false, starts_at: '2025-08-01', ends_at: '2025-08-31', sort_order: 4 },
  { id: 'promo-005', title: 'Back to School Internet', subtitle: 'For households with students', body: 'Students at home? Get faster speeds for online classes.', cta_text: 'Learn More', promo_type: 'new_plan', target_tags: ['student'], is_active: false, starts_at: '2025-08-01', ends_at: null, sort_order: 5 },
];

export const ADMIN_DEMO_REFERRALS = [
  { id: 'ref-001', referrer_name: 'Maria Santos', referrer_account: 'AV-BTG-10234', referrer_code: 'SANT-4821-BTG', referee_mobile: '09189876543', referral_type: 'subscriber', status: 'activated', reward_amount: 200, reward_type: 'bill_credit', reward_credited: true, activated_at: '2025-06-10T08:00:00Z', created_at: '2025-05-28T10:00:00Z' },
  { id: 'ref-002', referrer_name: 'Maria Santos', referrer_account: 'AV-BTG-10234', referrer_code: 'SANT-4821-BTG', referee_mobile: '09201112233', referral_type: 'subscriber', status: 'registered', reward_amount: null, reward_type: null, reward_credited: false, activated_at: null, created_at: '2025-07-01T15:00:00Z' },
  { id: 'ref-003', referrer_name: 'Jose Reyes', referrer_account: 'AV-BTG-10198', referrer_code: 'REYE-3310-BTG', referee_mobile: '09154445566', referral_type: 'subscriber', status: 'activated', reward_amount: 200, reward_type: 'bill_credit', reward_credited: true, activated_at: '2025-06-20T10:00:00Z', created_at: '2025-06-05T09:00:00Z' },
  { id: 'ref-004', referrer_name: 'Roberto Dela Torre', referrer_account: 'AV-ZAM-30012', referrer_code: 'DELA-9901-ZAM', referee_mobile: '09278889900', referral_type: 'subscriber', status: 'invited', reward_amount: null, reward_type: null, reward_credited: false, activated_at: null, created_at: '2025-07-07T14:00:00Z' },
  { id: 'ref-005', referrer_name: 'Ana Cruz', referrer_account: 'AV-QUE-20045', referrer_code: 'CRUZ-7742-QUE', referee_mobile: '09334445566', referral_type: 'subscriber', status: 'activated', reward_amount: 200, reward_type: 'bill_credit', reward_credited: false, activated_at: '2025-07-05T11:00:00Z', created_at: '2025-06-18T08:00:00Z' },
  { id: 'ref-006', referrer_name: 'Jose Reyes', referrer_account: 'AV-BTG-10198', referrer_code: 'REYE-3310-BTG', referee_mobile: '09451237890', referral_type: 'employee', status: 'activated', reward_amount: 500, reward_type: 'bill_credit', reward_credited: true, activated_at: '2025-07-02T09:00:00Z', created_at: '2025-06-10T11:00:00Z' },
];

export const ADMIN_DEMO_SERVICE_AREAS = [
  { id: 'sa-001', province: 'Batangas', municipality: 'Lipa City', barangay: 'San Jose', is_serviceable: true, waitlist_count: 0 },
  { id: 'sa-002', province: 'Batangas', municipality: 'Lipa City', barangay: 'San Pedro', is_serviceable: true, waitlist_count: 2 },
  { id: 'sa-003', province: 'Batangas', municipality: 'Batangas City', barangay: 'Kumintang Ibaba', is_serviceable: true, waitlist_count: 0 },
  { id: 'sa-004', province: 'Batangas', municipality: 'Batangas City', barangay: 'Pallocan West', is_serviceable: true, waitlist_count: 1 },
  { id: 'sa-005', province: 'Batangas', municipality: 'Tanauan City', barangay: 'Natatas', is_serviceable: false, waitlist_count: 14 },
  { id: 'sa-006', province: 'Batangas', municipality: 'Tanauan City', barangay: 'Ulango', is_serviceable: false, waitlist_count: 8 },
  { id: 'sa-007', province: 'Batangas', municipality: 'Santo Tomas', barangay: 'Sto. Tomas Proper', is_serviceable: true, waitlist_count: 0 },
  { id: 'sa-008', province: 'Quezon Province', municipality: 'Lucena City', barangay: 'Ibabang Dupay', is_serviceable: true, waitlist_count: 3 },
  { id: 'sa-009', province: 'Quezon Province', municipality: 'Lucena City', barangay: 'Mayao Kanluran', is_serviceable: true, waitlist_count: 0 },
  { id: 'sa-010', province: 'Quezon Province', municipality: 'Lucban', barangay: 'Poblacion', is_serviceable: false, waitlist_count: 22 },
  { id: 'sa-011', province: 'Quezon Province', municipality: 'Tayabas City', barangay: 'Silangan', is_serviceable: false, waitlist_count: 11 },
  { id: 'sa-012', province: 'Zambales', municipality: 'Olongapo City', barangay: 'Barretto', is_serviceable: true, waitlist_count: 0 },
  { id: 'sa-013', province: 'Zambales', municipality: 'Olongapo City', barangay: 'East Bajac-Bajac', is_serviceable: true, waitlist_count: 1 },
  { id: 'sa-014', province: 'Zambales', municipality: 'Subic', barangay: 'Calapacuan', is_serviceable: false, waitlist_count: 17 },
  { id: 'sa-015', province: 'Zambales', municipality: 'Iba', barangay: 'Poblacion', is_serviceable: false, waitlist_count: 9 },
];

export const ADMIN_DEMO_UPGRADES = [
  { id: 'upg-001', subscriber_name: 'Maria Santos', account_number: 'AV-BTG-10234', current_plan: 'Fiber 100 Mbps', requested_plan: 'Fiber 200 Mbps', current_fee: 1799, new_fee: 2499, status: 'pending', notes: 'OFW household, needs more bandwidth for video calls', assigned_agent: null, scheduled_date: null, created_at: '2025-07-08T10:00:00Z', hubspot_deal_id: 'hs-deal-001' },
  { id: 'upg-002', subscriber_name: 'Roberto Dela Torre', account_number: 'AV-ZAM-30012', current_plan: 'Fiber 200 Mbps', requested_plan: 'Fiber 500 Mbps', current_fee: 2499, new_fee: 3299, status: 'contacted', notes: 'WFH + gaming household. Agent called July 8.', assigned_agent: 'Jomar Santos', scheduled_date: '2025-07-12', created_at: '2025-07-06T14:00:00Z', hubspot_deal_id: 'hs-deal-002' },
  { id: 'upg-003', subscriber_name: 'Carla Mendoza', account_number: 'AV-BTG-10301', current_plan: 'Fiber 50 Mbps', requested_plan: 'Fiber 100 Mbps', current_fee: 1299, new_fee: 1799, status: 'scheduled', notes: 'Student household upgrade before school year.', assigned_agent: 'Ana Reyes', scheduled_date: '2025-07-11', created_at: '2025-07-03T09:00:00Z', hubspot_deal_id: 'hs-deal-003' },
  { id: 'upg-004', subscriber_name: 'Ramon Flores', account_number: 'AV-QUE-20088', current_plan: 'Fiber 100 Mbps', requested_plan: 'Fiber 200 Mbps', current_fee: 1799, new_fee: 2499, status: 'completed', notes: 'Installation completed successfully.', assigned_agent: 'Jomar Santos', scheduled_date: '2025-07-05', created_at: '2025-06-28T11:00:00Z', hubspot_deal_id: 'hs-deal-004' },
  { id: 'upg-005', subscriber_name: 'Grace Villanueva', account_number: 'AV-BTG-10412', current_plan: 'Fiber 50 Mbps', requested_plan: 'Fiber 200 Mbps', current_fee: 1299, new_fee: 2499, status: 'cancelled', notes: 'Subscriber cancelled - moving residences.', assigned_agent: 'Ana Reyes', scheduled_date: null, created_at: '2025-06-25T16:00:00Z', hubspot_deal_id: 'hs-deal-005' },
  { id: 'upg-006', subscriber_name: 'Benjamin Cruz', account_number: 'AV-ZAM-30045', current_plan: 'Fiber 100 Mbps', requested_plan: 'Fiber 500 Mbps', current_fee: 1799, new_fee: 3299, status: 'pending', notes: 'Business use - multiple remote workers.', assigned_agent: null, scheduled_date: null, created_at: '2025-07-09T08:00:00Z', hubspot_deal_id: null },
  { id: 'upg-007', subscriber_name: 'Lourdes Bautista', account_number: 'AV-QUE-20102', current_plan: 'Fiber 50 Mbps', requested_plan: 'Fiber 100 Mbps', current_fee: 1299, new_fee: 1799, status: 'contacted', notes: 'Has OFW family member, recommended 100 plan.', assigned_agent: 'Jomar Santos', scheduled_date: null, created_at: '2025-07-07T13:00:00Z', hubspot_deal_id: 'hs-deal-007' },
];

export const ADMIN_DEMO_PLANS = [
  {
    id: 'plan-001',
    plan_code: 'FIBER-50',
    plan_name: 'Fiber 50',
    plan_type: 'fiber',
    speed_down_mbps: 50,
    speed_up_mbps: 50,
    monthly_fee: 1299,
    install_fee: 0,
    contract_months: 12,
    description: 'Perfect for light browsing and streaming',
    features: ['50 Mbps download', '50 Mbps upload', 'No data cap', 'Free installation'],
    is_active: true,
    is_featured: false,
    tags: ['starter'],
    subscriber_count: 312,
    pending_upgrades: 2,
    monthly_revenue: 405288,
  },
  {
    id: 'plan-002',
    plan_code: 'FIBER-100',
    plan_name: 'Fiber 100',
    plan_type: 'fiber',
    speed_down_mbps: 100,
    speed_up_mbps: 100,
    monthly_fee: 1799,
    install_fee: 0,
    contract_months: 12,
    description: 'Ideal for families with multiple devices',
    features: ['100 Mbps download', '100 Mbps upload', 'No data cap', 'Free installation', 'Free modem'],
    is_active: true,
    is_featured: true,
    tags: ['popular', 'family'],
    subscriber_count: 874,
    pending_upgrades: 5,
    monthly_revenue: 1571426,
  },
  {
    id: 'plan-003',
    plan_code: 'FIBER-200',
    plan_name: 'Fiber 200',
    plan_type: 'fiber',
    speed_down_mbps: 200,
    speed_up_mbps: 200,
    monthly_fee: 2499,
    install_fee: 0,
    contract_months: 12,
    description: 'Best for work-from-home and gaming households',
    features: ['200 Mbps download', '200 Mbps upload', 'No data cap', 'Free installation', 'Free modem', 'Priority support'],
    is_active: true,
    is_featured: false,
    tags: ['wfh', 'gaming', 'ofw'],
    subscriber_count: 498,
    pending_upgrades: 7,
    monthly_revenue: 1244502,
  },
  {
    id: 'plan-004',
    plan_code: 'FIBER-500',
    plan_name: 'Fiber 500',
    plan_type: 'fiber',
    speed_down_mbps: 500,
    speed_up_mbps: 500,
    monthly_fee: 3299,
    install_fee: 0,
    contract_months: 12,
    description: 'Ultra-fast for heavy users and businesses',
    features: ['500 Mbps download', '500 Mbps upload', 'No data cap', 'Free installation', 'Free modem', 'Dedicated support', 'Static IP available'],
    is_active: true,
    is_featured: false,
    tags: ['business', 'gaming'],
    subscriber_count: 163,
    pending_upgrades: 3,
    monthly_revenue: 537737,
  },
  {
    id: 'plan-005',
    plan_code: 'CABLE-BASIC',
    plan_name: 'Cable Basic',
    plan_type: 'cable',
    speed_down_mbps: 25,
    speed_up_mbps: 5,
    monthly_fee: 799,
    install_fee: 500,
    contract_months: 0,
    description: 'Entry-level cable internet for casual users',
    features: ['25 Mbps download', '5 Mbps upload', 'No contract', 'Standard support'],
    is_active: false,
    is_featured: false,
    tags: ['legacy'],
    subscriber_count: 0,
    pending_upgrades: 0,
    monthly_revenue: 0,
  },
  {
    id: 'plan-006',
    plan_code: 'BUNDLE-FIBER-TV',
    plan_name: 'Fiber + TV Bundle',
    plan_type: 'bundle',
    speed_down_mbps: 100,
    speed_up_mbps: 100,
    monthly_fee: 2199,
    install_fee: 0,
    contract_months: 24,
    description: 'Fiber 100 internet plus cable TV channels',
    features: ['100 Mbps internet', '80+ cable channels', 'Free installation', 'Free modem + cable box', '2-year lock-in'],
    is_active: true,
    is_featured: false,
    tags: ['bundle', 'family'],
    subscriber_count: 0,
    pending_upgrades: 0,
    monthly_revenue: 0,
  },
];

export const ADMIN_DEMO_INVOICES = [
  {
    id: 'inv-001', invoice_number: '#AV-INV-2025-0610',
    subscriber_name: 'Maria Santos', account_number: 'AV-BTG-10234',
    email: 'maria.santos@gmail.com', address: '123 Rizal St, San Pedro, Lipa City, Batangas',
    plan: 'Fiber 100 Mbps', billing_period: 'June 1-30, 2025',
    date: '2025-07-01', due_date: '2025-07-15',
    items: [{ desc: 'Fiber 100 Mbps - Monthly Subscription', detail: 'Billing period: June 1-30, 2025', rate: 1799, qty: 1 }],
    subtotal: 1799, tax: 0, discount: 0, shipping: 0, total: 1799,
    status: 'unpaid', payment_method: null,
  },
  {
    id: 'inv-002', invoice_number: '#AV-INV-2025-0609',
    subscriber_name: 'Jose Reyes', account_number: 'AV-BTG-10198',
    email: 'jose.reyes@gmail.com', address: '45 Mabini St, Kumintang Ibaba, Batangas City',
    plan: 'Fiber 50 Mbps', billing_period: 'June 1-30, 2025',
    date: '2025-07-01', due_date: '2025-07-15',
    items: [{ desc: 'Fiber 50 Mbps - Monthly Subscription', detail: 'Billing period: June 1-30, 2025', rate: 1299, qty: 1 }],
    subtotal: 1299, tax: 0, discount: 0, shipping: 0, total: 1299,
    status: 'paid', payment_method: 'GCash',
  },
  {
    id: 'inv-003', invoice_number: '#AV-INV-2025-0608',
    subscriber_name: 'Ana Cruz', account_number: 'AV-QUE-20045',
    email: 'ana.cruz@yahoo.com', address: 'B5 L12 Ibabang Dupay, Lucena City, Quezon Province',
    plan: 'Fiber 100 Mbps', billing_period: 'May 1-31, 2025',
    date: '2025-06-01', due_date: '2025-06-15',
    items: [
      { desc: 'Fiber 100 Mbps - Monthly Subscription', detail: 'Billing period: May 1-31, 2025', rate: 1799, qty: 1 },
      { desc: 'Late Payment Penalty', detail: 'Payment received after due date', rate: 100, qty: 1 },
    ],
    subtotal: 1899, tax: 0, discount: 0, shipping: 0, total: 1899,
    status: 'overdue', payment_method: null,
  },
  {
    id: 'inv-004', invoice_number: '#AV-INV-2025-0607',
    subscriber_name: 'Roberto Dela Torre', account_number: 'AV-ZAM-30012',
    email: null, address: '22 Barretto Beach Rd, Olongapo City, Zambales',
    plan: 'Fiber 200 Mbps', billing_period: 'June 1-30, 2025',
    date: '2025-07-01', due_date: '2025-07-15',
    items: [{ desc: 'Fiber 200 Mbps - Monthly Subscription', detail: 'Billing period: June 1-30, 2025', rate: 2499, qty: 1 }],
    subtotal: 2499, tax: 0, discount: 0, shipping: 0, total: 2499,
    status: 'paid', payment_method: 'Bank Transfer',
  },
  {
    id: 'inv-005', invoice_number: '#AV-INV-2025-0606',
    subscriber_name: 'Maria Santos', account_number: 'AV-BTG-10234',
    email: 'maria.santos@gmail.com', address: '123 Rizal St, San Pedro, Lipa City, Batangas',
    plan: 'Fiber 100 Mbps', billing_period: 'May 1-31, 2025',
    date: '2025-06-01', due_date: '2025-06-15',
    items: [
      { desc: 'Fiber 100 Mbps - Monthly Subscription', detail: 'Billing period: May 1-31, 2025', rate: 1799, qty: 1 },
      { desc: 'Installation Fee Waiver', detail: 'Promotional discount', rate: -0, qty: 1 },
    ],
    subtotal: 1799, tax: 0, discount: 0, shipping: 0, total: 1799,
    status: 'paid', payment_method: 'Maya',
  },
  {
    id: 'inv-006', invoice_number: '#AV-INV-2025-0605',
    subscriber_name: 'Jose Reyes', account_number: 'AV-BTG-10198',
    email: 'jose.reyes@gmail.com', address: '45 Mabini St, Kumintang Ibaba, Batangas City',
    plan: 'Fiber 50 Mbps', billing_period: 'April 1-30, 2025',
    date: '2025-05-01', due_date: '2025-05-15',
    items: [{ desc: 'Fiber 50 Mbps - Monthly Subscription', detail: 'Billing period: April 1-30, 2025', rate: 1299, qty: 1 }],
    subtotal: 1299, tax: 0, discount: 0, shipping: 0, total: 1299,
    status: 'cancelled', payment_method: null,
  },
];

export type Invoice = typeof ADMIN_DEMO_INVOICES[0];

export const ADMIN_METRICS = {
  active_subscribers: 1847,
  app_users_30d: 623,
  outstanding_bills_total: 384250,
  open_tickets: 14,
  referrals_this_month: 23,
  pending_upgrades: 7,
};
