export const ADMIN_DEMO_SUBSCRIBERS = [
  {
    id: 'sub-001',
    account_number: 'AV-BTG-10234',
    first_name: 'Maria',
    last_name: 'Santos',
    mobile: '09171234567',
    email: 'maria.santos@gmail.com',
    province: 'Batangas',
    municipality: 'Lipa City',
    barangay: 'San Pedro',
    subscription_status: 'active',
    plan_name: 'Fiber 100 Mbps',
    monthly_fee: 1799,
    outstanding_balance: 1799,
    enrichment_pct: 37,
    points_balance: 230,
    referral_code: 'SANT-4821-BTG',
    app_last_login: '2025-07-09T08:00:00Z',
    hubspot_contact_id: 'hs-contact-001',
  },
  {
    id: 'sub-002',
    account_number: 'AV-BTG-10198',
    first_name: 'Jose',
    last_name: 'Reyes',
    mobile: '09289876543',
    email: 'jose.reyes@gmail.com',
    province: 'Batangas',
    municipality: 'Batangas City',
    barangay: 'Kumintang Ibaba',
    subscription_status: 'active',
    plan_name: 'Fiber 50 Mbps',
    monthly_fee: 1299,
    outstanding_balance: 0,
    enrichment_pct: 87,
    points_balance: 580,
    referral_code: 'REYE-3310-BTG',
    app_last_login: '2025-07-08T15:30:00Z',
    hubspot_contact_id: 'hs-contact-002',
  },
  {
    id: 'sub-003',
    account_number: 'AV-QUE-20045',
    first_name: 'Ana',
    last_name: 'Cruz',
    mobile: '09151112233',
    email: 'ana.cruz@yahoo.com',
    province: 'Quezon Province',
    municipality: 'Lucena City',
    barangay: 'Ibabang Dupay',
    subscription_status: 'suspended',
    plan_name: 'Fiber 100 Mbps',
    monthly_fee: 1799,
    outstanding_balance: 3598,
    enrichment_pct: 12,
    points_balance: 50,
    referral_code: 'CRUZ-7742-QUE',
    app_last_login: '2025-06-15T10:00:00Z',
    hubspot_contact_id: null,
  },
  {
    id: 'sub-004',
    account_number: 'AV-ZAM-30012',
    first_name: 'Roberto',
    last_name: 'Dela Torre',
    mobile: '09334445566',
    email: null,
    province: 'Zambales',
    municipality: 'Olongapo City',
    barangay: 'Barretto',
    subscription_status: 'active',
    plan_name: 'Fiber 200 Mbps',
    monthly_fee: 2499,
    outstanding_balance: 0,
    enrichment_pct: 62,
    points_balance: 310,
    referral_code: 'DELA-9901-ZAM',
    app_last_login: '2025-07-09T07:45:00Z',
    hubspot_contact_id: 'hs-contact-004',
  },
];

export const ADMIN_DEMO_TICKETS = [
  {
    id: 'tkt-001',
    ticket_number: 'AV-TKT-20250010',
    subscriber_name: 'Maria Santos',
    account_number: 'AV-BTG-10234',
    ticket_type: 'technical',
    category: 'Slow speed',
    subject: 'Internet is slower than usual during evenings',
    status: 'in_progress',
    priority: 'normal',
    created_at: '2025-07-05T10:00:00Z',
    hubspot_ticket_id: 'hs-tkt-001',
  },
  {
    id: 'tkt-002',
    ticket_number: 'AV-TKT-20250009',
    subscriber_name: 'Ana Cruz',
    account_number: 'AV-QUE-20045',
    ticket_type: 'billing',
    category: 'Payment not reflected',
    subject: 'Paid last month but account still shows overdue',
    status: 'open',
    priority: 'high',
    created_at: '2025-07-03T14:00:00Z',
    hubspot_ticket_id: null,
  },
  {
    id: 'tkt-003',
    ticket_number: 'AV-TKT-20250008',
    subscriber_name: 'Jose Reyes',
    account_number: 'AV-BTG-10198',
    ticket_type: 'technical',
    category: 'No internet',
    subject: 'Complete internet outage after storm',
    status: 'resolved',
    priority: 'urgent',
    created_at: '2025-07-01T09:00:00Z',
    hubspot_ticket_id: 'hs-tkt-003',
  },
];

export const ADMIN_DEMO_HUBSPOT_LOGS = [
  { id: 'hs-1', entity_type: 'subscriber', entity_id: 'sub-001', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-09T08:00:00Z', error_message: null },
  { id: 'hs-2', entity_type: 'ticket', entity_id: 'tkt-001', hubspot_object_type: 'ticket', action: 'create', status: 'success', synced_at: '2025-07-05T10:01:00Z', error_message: null },
  { id: 'hs-3', entity_type: 'subscriber', entity_id: 'sub-003', hubspot_object_type: 'contact', action: 'create', status: 'failed', synced_at: null, error_message: 'Invalid phone format for HubSpot contact' },
  { id: 'hs-4', entity_type: 'ticket', entity_id: 'tkt-002', hubspot_object_type: 'ticket', action: 'create', status: 'pending', synced_at: null, error_message: null },
  { id: 'hs-5', entity_type: 'subscriber', entity_id: 'sub-004', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-09T07:46:00Z', error_message: null },
  { id: 'hs-6', entity_type: 'payment', entity_id: 'pay-002', hubspot_object_type: 'contact', action: 'update', status: 'success', synced_at: '2025-07-08T12:00:00Z', error_message: null },
];

export const ADMIN_METRICS = {
  active_subscribers: 1847,
  app_users_30d: 623,
  outstanding_bills_total: 384250,
  open_tickets: 14,
  referrals_this_month: 23,
  pending_upgrades: 7,
};
