import type { Subscriber, Bill, Device, Ticket, TicketUpdate, Plan, EnrichmentProfile, EnrichmentQuestion, Referral, Notification, Promo, SubscriberPlan } from '../types';

export const DEMO_SUBSCRIBER: Subscriber = {
  id: 'sub-001',
  auth_user_id: 'auth-001',
  account_number: 'AV-BTG-10234',
  first_name: 'Maria',
  last_name: 'Santos',
  mobile: '09171234567',
  email: 'maria.santos@gmail.com',
  service_address: '123 Rizal Street, Brgy. San Pedro',
  province: 'Batangas',
  municipality: 'Lipa City',
  barangay: 'San Pedro',
  subscriber_type: 'residential',
  subscription_status: 'active',
  is_employee: false,
  referral_code: 'SANT-4821-BTG',
  points_balance: 230,
  enrichment_score: 3,
  enrichment_pct: 37,
  app_last_login: new Date().toISOString(),
};

export const DEMO_CURRENT_PLAN: SubscriberPlan = {
  id: 'sp-001',
  subscriber_id: 'sub-001',
  plan_code: 'FIBER-100',
  plan_name: 'Fiber 100 Mbps',
  monthly_fee: 1799,
  speed_down_mbps: 100,
  speed_up_mbps: 100,
  activation_date: '2024-01-15',
  contract_end_date: '2025-01-15',
  lock_in_months: 12,
  is_primary: true,
};

export const DEMO_BILLS: Bill[] = [
  {
    id: 'bill-001',
    subscriber_id: 'sub-001',
    bill_number: 'AV-2025-0607',
    billing_period_start: '2025-06-01',
    billing_period_end: '2025-06-30',
    due_date: '2025-07-15',
    amount_due: 1799,
    amount_paid: 0,
    balance: 1799,
    status: 'unpaid',
  },
  {
    id: 'bill-002',
    subscriber_id: 'sub-001',
    bill_number: 'AV-2025-0506',
    billing_period_start: '2025-05-01',
    billing_period_end: '2025-05-31',
    due_date: '2025-06-15',
    amount_due: 1799,
    amount_paid: 1799,
    balance: 0,
    status: 'paid',
  },
  {
    id: 'bill-003',
    subscriber_id: 'sub-001',
    bill_number: 'AV-2025-0405',
    billing_period_start: '2025-04-01',
    billing_period_end: '2025-04-30',
    due_date: '2025-05-15',
    amount_due: 1799,
    amount_paid: 1799,
    balance: 0,
    status: 'paid',
  },
];

export const DEMO_DEVICE: Device = {
  id: 'dev-001',
  subscriber_id: 'sub-001',
  device_model: 'ZTE F660P ONU',
  serial_number: 'ZTEG-A1B2C3D4',
  mac_address: '00:1A:2B:3C:4D:5E',
  firmware_version: 'V1.2.3_P45',
  installation_date: '2024-01-15',
  is_active: true,
  last_seen: new Date().toISOString(),
  cpe_status: 'online',
  signal_tx: -3.2,
  signal_rx: -18.5,
  signal_quality: 'good',
  restart_count_7d: 0,
};

export const DEMO_TICKETS: Ticket[] = [
  {
    id: 'tkt-001',
    ticket_number: 'AV-TKT-20250010',
    subscriber_id: 'sub-001',
    ticket_type: 'technical',
    category: 'Slow speed',
    subject: 'Internet is slower than usual during evenings',
    description: 'Connection drops to around 10-15 Mbps after 7pm.',
    photos: [],
    status: 'in_progress',
    priority: 'normal',
    self_help_attempted: true,
    created_at: '2025-07-05T10:00:00Z',
    updated_at: '2025-07-06T14:30:00Z',
  },
];

export const DEMO_TICKET_UPDATES: TicketUpdate[] = [
  {
    id: 'tu-001',
    ticket_id: 'tkt-001',
    status: 'open',
    message: 'Your ticket has been received. We will investigate the issue.',
    updated_by: 'system',
    created_at: '2025-07-05T10:00:00Z',
  },
  {
    id: 'tu-002',
    ticket_id: 'tkt-001',
    status: 'in_progress',
    message: 'Our technical team has identified potential congestion in your area. We are working on a fix.',
    updated_by: 'support_agent',
    created_at: '2025-07-06T14:30:00Z',
  },
];

export const DEMO_PLANS: Plan[] = [
  {
    id: 'plan-001',
    plan_code: 'FIBER-50',
    plan_name: 'Fiber 50',
    plan_type: 'fiber',
    speed_down_mbps: 50,
    speed_up_mbps: 50,
    monthly_fee: 1299,
    install_fee: 0,
    contract_months: 12,
    description: 'Perfect for light browsing and streaming',
    features: ['50 Mbps download', '50 Mbps upload', 'No data cap', 'Free installation'],
    is_active: true,
    is_featured: false,
    tags: ['starter'],
  },
  {
    id: 'plan-002',
    plan_code: 'FIBER-100',
    plan_name: 'Fiber 100',
    plan_type: 'fiber',
    speed_down_mbps: 100,
    speed_up_mbps: 100,
    monthly_fee: 1799,
    install_fee: 0,
    contract_months: 12,
    description: 'Ideal for families with multiple devices',
    features: ['100 Mbps download', '100 Mbps upload', 'No data cap', 'Free installation', 'Free modem'],
    is_active: true,
    is_featured: true,
    tags: ['popular', 'family'],
  },
  {
    id: 'plan-003',
    plan_code: 'FIBER-200',
    plan_name: 'Fiber 200',
    plan_type: 'fiber',
    speed_down_mbps: 200,
    speed_up_mbps: 200,
    monthly_fee: 2499,
    install_fee: 0,
    contract_months: 12,
    description: 'Best for work-from-home and gaming households',
    features: ['200 Mbps download', '200 Mbps upload', 'No data cap', 'Free installation', 'Free modem', 'Priority support'],
    is_active: true,
    is_featured: false,
    tags: ['wfh', 'gaming', 'ofw'],
  },
  {
    id: 'plan-004',
    plan_code: 'FIBER-500',
    plan_name: 'Fiber 500',
    plan_type: 'fiber',
    speed_down_mbps: 500,
    speed_up_mbps: 500,
    monthly_fee: 3299,
    install_fee: 0,
    contract_months: 12,
    description: 'Ultra-fast for heavy users and businesses',
    features: ['500 Mbps download', '500 Mbps upload', 'No data cap', 'Free installation', 'Free modem', 'Dedicated support line', 'Static IP available'],
    is_active: true,
    is_featured: false,
    tags: ['business', 'gaming'],
  },
];

export const DEMO_ENRICHMENT: EnrichmentProfile = {
  id: 'enr-001',
  subscriber_id: 'sub-001',
  has_ofw_member: true,
  device_types: ['Smartphones', 'Laptops'],
  primary_usage: [],
  streaming_services: ['Netflix', 'YouTube'],
  answers: {
    has_ofw_member: true,
    device_types: ['Smartphones', 'Laptops'],
    streaming_services: ['Netflix', 'YouTube'],
  },
  completed_questions: 3,
  total_questions: 8,
};

export const DEMO_ENRICHMENT_QUESTIONS: EnrichmentQuestion[] = [
  {
    id: 'eq-1',
    question_key: 'household_size',
    question_text: 'How many people live in your household?',
    answer_type: 'select',
    options: ['Just me', '2-3 people', '4-5 people', '6 or more'],
    points_reward: 50,
    hubspot_property: 'household_size',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'eq-2',
    question_key: 'has_wfh_member',
    question_text: 'Does anyone in your household work from home regularly?',
    answer_type: 'boolean',
    points_reward: 40,
    hubspot_property: 'has_wfh_member',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'eq-3',
    question_key: 'has_student_user',
    question_text: 'Do your children use the internet for school or online learning?',
    answer_type: 'boolean',
    points_reward: 40,
    hubspot_property: 'has_student_user',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'eq-4',
    question_key: 'has_gaming_user',
    question_text: 'Does anyone in the household game online?',
    answer_type: 'boolean',
    points_reward: 40,
    hubspot_property: 'has_gaming_user',
    sort_order: 4,
    is_active: true,
  },
  {
    id: 'eq-5',
    question_key: 'contact_preference',
    question_text: 'How would you prefer us to contact you?',
    answer_type: 'select',
    options: ['SMS', 'Email', 'Phone call'],
    points_reward: 20,
    hubspot_property: 'preferred_contact_method',
    sort_order: 5,
    is_active: true,
  },
];

export const DEMO_REFERRALS: Referral[] = [
  {
    id: 'ref-001',
    referrer_id: 'sub-001',
    referrer_code: 'SANT-4821-BTG',
    referee_mobile: '09189876543',
    referral_type: 'subscriber',
    status: 'activated',
    reward_amount: 200,
    reward_type: 'bill_credit',
    reward_credited: true,
    activated_at: '2025-06-10T08:00:00Z',
    created_at: '2025-05-28T10:00:00Z',
  },
  {
    id: 'ref-002',
    referrer_id: 'sub-001',
    referrer_code: 'SANT-4821-BTG',
    referee_mobile: '09201112233',
    referral_type: 'subscriber',
    status: 'registered',
    reward_credited: false,
    created_at: '2025-07-01T15:00:00Z',
  },
  {
    id: 'ref-003',
    referrer_id: 'sub-001',
    referrer_code: 'SANT-4821-BTG',
    referee_mobile: '09154445566',
    referral_type: 'subscriber',
    status: 'invited',
    reward_credited: false,
    created_at: '2025-07-07T09:00:00Z',
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    subscriber_id: 'sub-001',
    type: 'billing',
    title: 'Bill Ready',
    body: 'Your June 2025 bill of PHP 1,799 is now available. Due: July 15.',
    is_read: false,
    created_at: '2025-07-01T08:00:00Z',
  },
  {
    id: 'notif-002',
    subscriber_id: 'sub-001',
    type: 'referral',
    title: 'Referral Activated!',
    body: 'Your referral earned you PHP 200 bill credit.',
    is_read: false,
    created_at: '2025-06-10T10:00:00Z',
  },
  {
    id: 'notif-003',
    subscriber_id: 'sub-001',
    type: 'support',
    title: 'Ticket Update',
    body: 'Our team is now working on your connection issue (AV-TKT-20250010).',
    is_read: true,
    created_at: '2025-07-06T14:30:00Z',
  },
  {
    id: 'notif-004',
    subscriber_id: 'sub-001',
    type: 'promo',
    title: 'Special Offer for OFW Families',
    body: 'Upgrade to Fiber 200 and get 2 months free. Perfect for families with members abroad.',
    is_read: true,
    created_at: '2025-06-25T09:00:00Z',
  },
];

export const DEMO_PROMOS: Promo[] = [
  {
    id: 'promo-001',
    title: 'OFW Family Package',
    subtitle: 'Stay connected with family abroad',
    body: 'Upgrade to Fiber 200 - get 2 months free!',
    cta_text: 'Learn More',
    promo_type: 'discount',
    is_active: true,
    starts_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'promo-002',
    title: 'Refer a Neighbor',
    subtitle: 'Earn PHP 200 bill credit',
    body: 'Every successful referral gives you PHP 200 off your next bill.',
    cta_text: 'Share My Code',
    promo_type: 'announcement',
    is_active: true,
    starts_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 'promo-003',
    title: 'Free Installation',
    subtitle: 'Until July 31, 2025',
    body: 'New subscribers get free installation on all Fiber plans.',
    cta_text: 'Refer a Friend',
    promo_type: 'discount',
    is_active: true,
    starts_at: '2025-07-01T00:00:00Z',
    ends_at: '2025-07-31T23:59:59Z',
  },
];
